include:
  - remote: https://raw.githubusercontent.com/edersonbrilhante/vilicus-gitlab/main/Vilicus.gitlab-ci.yml  

remote_image:
  extends: .vilicus
  variables:
    IMAGE: python
  tags:
    - crosscicd

local_image:
  extends: .vilicus
  variables:
    IMAGE: localhost:5000/local-image:${CI_COMMIT_SHORT_SHA}
  script:
    - docker build -t localhost:5000/local-image:${CI_COMMIT_SHORT_SHA} .
    - ./run-job.sh
  tags:
    - crosscicd